# Currently not working

version: '3.4'
services:
  
  molitio-ui:
    build: './ui/molitio-ui'
    image: 'molitio-ui'
    ports: 
      # - 80:80
      # - 443:443
      - 4200:4200
      - 4201:4201
    #environment: 
      # - ENV=dev
    restart: always
    
  #molitio-api:
   # build: './molitio-api'
    #volumes: 
     # - .:/usr/app/
      #- /usr/app/node_modules
    #ports:
     # - "3000:3000"
    #environment: 
     # NODE_ENV: development
      #NODE_ENV: production
    #restart: always

